[manager]

append_keymap = [
    { on = [ "g", "l" ], run = "cd ~/.dotfiles", desc = "Go to the dotfiles directory" },
    { on = [ "g", "a" ], run = "cd %APPDATA%",   desc = "Got to app data directory"},
]
